arm1_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm1_J1
    - arm1_J2
    - arm1_J3
    - arm1_J4
    - arm1_J5
    - arm1_J621
  gains:
    arm1_J1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_J2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_J3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_J4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_J5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_J621:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm2_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm2_J1
    - arm2_J2
    - arm2_J3
    - arm2_J4
    - arm2_J5
    - arm2_J621
  gains:
    arm2_J1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm2_J2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm2_J3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm2_J4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm2_J5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm2_J621:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm3_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm3_J1
    - arm3_J2
    - arm3_J3
    - arm3_J4
    - arm3_J5
    - arm3_J621
  gains:
    arm3_J1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm3_J2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm3_J3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm3_J4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm3_J5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm3_J621:
      p: 100
      d: 1
      i: 1
      i_clamp: 1